name: Run UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Verify Chrome is installed
        run: |
          google-chrome --version
          chromedriver --version

      - name: Run tests with Maven (headless Chrome)
        run: mvn clean test -Dheadless=true

      - name: Upload Cucumber HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Cucumber HTML Report
          path: target/CucumberReports/cucumber-reports.html
